/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as BreedsRouteImport } from './routes/breeds'
import { Route as BreedsSlugRouteImport } from './routes/breeds.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const BreedsRoute = BreedsRouteImport.update({
  id: '/breeds',
  path: '/breeds',
  getParentRoute: () => rootRouteImport,
} as any)
const BreedsSlugRoute = BreedsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BreedsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/breeds': typeof BreedsRouteWithChildren
  '/breeds/$slug': typeof BreedsSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/breeds': typeof BreedsRouteWithChildren
  '/breeds/$slug': typeof BreedsSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/breeds': typeof BreedsRouteWithChildren
  '/breeds/$slug': typeof BreedsSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/breeds' | '/breeds/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/breeds' | '/breeds/$slug'
  id: '__root__' | '/' | '/about' | '/breeds' | '/breeds/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BreedsRoute: typeof BreedsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/breeds': {
      id: '/breeds'
      path: '/breeds'
      fullPath: '/breeds'
      preLoaderRoute: typeof BreedsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/breeds/$slug': {
      id: '/breeds/$slug'
      path: '/$slug'
      fullPath: '/breeds/$slug'
      preLoaderRoute: typeof BreedsSlugRouteImport
      parentRoute: typeof BreedsRoute
    }
  }
}

interface BreedsRouteChildren {
  BreedsSlugRoute: typeof BreedsSlugRoute
}

const BreedsRouteChildren: BreedsRouteChildren = {
  BreedsSlugRoute: BreedsSlugRoute,
}

const BreedsRouteWithChildren =
  BreedsRoute._addFileChildren(BreedsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BreedsRoute: BreedsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
